name: Mack AWS workflow
on:
  push
env:
  AWS_REGION : "eu-west-1" 
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  AssumeRolenGetFlag:
    runs-on: ubuntu-latest
    steps:
      - name: Git Actions
        uses: actions/checkout@v3
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::520091917895:role/magichk_role
          aws-region: ${{ env.AWS_REGION }}
      - name: Run STS id
        run: |
          aws sts get-caller-identity